global:
  sendAnonymousUsage: false
  checkNewVersion: false

entryPoints:
  web:
    address: ":8080"

api:
  dashboard: false
  insecure: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: axion_edge
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

accessLog: {}

log:
  level: INFO
